apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/namsic/n4c-manifests.git
    path: manifests/default
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
